nsert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '323', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '324', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '325', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '326', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '333', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '334', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '335', 'N', 0.000, '', null, null, 'DUMMY', '0', '');



insert into XX_NEW_CHECKS_TABLE (ORG_CODE, ACCOUNT_NO, CHECK_BOOK_NO, CHECK_NO, STATUS, AMOUNT, BENEFICIARY, PRESENTATION_DATE, VALUE_DATE, REMARKS, CHECK_DIGIT, REJECT_CODE)

values ('100', '1008983382', '321', '336', 'N', 0.000, '', null, null, 'DUMMY', '0', '');




